package pluginonboarding

import (
	"fmt"
	"regexp"
	"sort"
	"strconv"
	"strings"

	"github.com/distribution/reference"
	"github.com/sholdee/drydock/internal/pluginpolicy"
)

const schemaModeline = SchemaModeline

func Generate(report Report, opts GenerateOptions) ([]byte, error) {
	if opts.Engine == "" {
		opts.Engine = pluginpolicy.EngineContainer
	}
	if opts.Engine != pluginpolicy.EngineContainer && opts.Engine != pluginpolicy.EngineExec {
		return nil, fmt.Errorf("plugin-policy init supports engine %q or %q", pluginpolicy.EngineContainer, pluginpolicy.EngineExec)
	}
	if err := validateBootstrapHints(report); err != nil {
		return nil, err
	}
	var b strings.Builder
	b.WriteString(schemaModeline)
	b.WriteByte('\n')
	if opts.Comments {
		b.WriteString("# Generated by drydock plugin-policy init. Review trust choices before using this policy in CI.\n")
	}
	b.WriteString("apiVersion: drydock.sholdee.dev/v1alpha1\n")
	b.WriteString("kind: PluginPolicy\n")
	writeBootstrap(&b, report, opts)
	b.WriteString("plugins:\n")
	if len(report.Plugins) == 0 {
		b.WriteString("  {}\n")
	} else {
		for _, plugin := range report.Plugins {
			writePlugin(&b, plugin, opts)
		}
	}
	out := []byte(b.String())
	if _, err := pluginpolicy.Parse("generated plugin policy", out); err != nil {
		return nil, err
	}
	return out, nil
}

func writeBootstrap(b *strings.Builder, report Report, opts GenerateOptions) {
	entrypoints := bootstrapEntrypointsForPolicy(report)
	if len(entrypoints) == 0 {
		return
	}
	b.WriteString("bootstrap:\n")
	b.WriteString("  entrypoints:\n")
	seen := map[string]int{}
	for _, entrypoint := range entrypoints {
		sourcePath := cleanBootstrapSourcePath(entrypoint.SourcePath)
		name := bootstrapName(entrypoint.Plugin, sourcePath)
		if count := seen[name]; count > 0 {
			seen[name] = count + 1
			name = trimDNSLabel(fmt.Sprintf("%s-%d", name, count+1))
		} else {
			seen[name] = 1
		}
		b.WriteString("    - name: " + quote(name) + "\n")
		b.WriteString("      plugin: " + quote(entrypoint.Plugin) + "\n")
		b.WriteString("      sourcePath: " + quote(sourcePath) + "\n")
	}
}

func bootstrapEntrypointsForPolicy(report Report) []BootstrapEntrypointHint {
	if len(report.BootstrapEntrypoints) == 0 {
		return nil
	}
	discoverByPlugin := map[string]bool{}
	for _, plugin := range report.Plugins {
		discoverByPlugin[plugin.Name] = plugin.Discover != nil
	}
	seen := map[string]struct{}{}
	var out []BootstrapEntrypointHint
	for _, entrypoint := range report.BootstrapEntrypoints {
		plugin := strings.TrimSpace(entrypoint.Plugin)
		if plugin == "" || !discoverByPlugin[plugin] {
			continue
		}
		sourcePath := cleanBootstrapSourcePath(entrypoint.SourcePath)
		if sourcePath == "" {
			continue
		}
		key := plugin + "\x00" + sourcePath
		if _, ok := seen[key]; ok {
			continue
		}
		seen[key] = struct{}{}
		out = append(out, BootstrapEntrypointHint{Plugin: plugin, SourcePath: sourcePath})
	}
	sort.Slice(out, func(i, j int) bool {
		return out[i].Plugin+"\x00"+out[i].SourcePath < out[j].Plugin+"\x00"+out[j].SourcePath
	})
	return out
}

func writePlugin(b *strings.Builder, plugin PluginReport, opts GenerateOptions) {
	b.WriteString("  " + quote(plugin.Name) + ":\n")
	if opts.Comments && len(plugin.Uses) > 0 {
		b.WriteString("    # Used by " + quote(commentUseSummary(plugin.Uses)) + ".\n")
	}
	b.WriteString("    engine: " + string(opts.Engine) + "\n")
	if plugin.Discover != nil {
		writeMatchDiscover(b, plugin.Discover)
	}
	if plugin.CMP != nil {
		writeCMPSeed(b, plugin)
	}
	if opts.Engine == pluginpolicy.EngineContainer {
		writeContainerFields(b, plugin, opts)
	}
	b.WriteString("    copy:\n")
	b.WriteString("      scope: source\n")
	writeLifecycle(b, plugin, opts)
	writeEnv(b, plugin)
	writeParameters(b, plugin)
}

func writeCMPSeed(b *strings.Builder, plugin PluginReport) {
	if plugin.CMP == nil {
		return
	}
	command := cleanArgv(plugin.CMP.GenerateCommand)
	args := cleanArgv(plugin.CMP.GenerateArgs)
	if plugin.Discover == nil && len(command) == 0 && len(args) == 0 {
		return
	}
	var seed strings.Builder
	if plugin.Discover != nil {
		writeDirectDiscover(&seed, "      ", plugin.Discover)
	}
	if plugin.GenerateSafe && (len(command) > 0 || len(args) > 0) {
		seed.WriteString("      generate:\n")
		if len(command) > 0 {
			seed.WriteString("        command: " + yamlStringSequence(command) + "\n")
		}
		if len(args) > 0 {
			seed.WriteString("        args: " + yamlStringSequence(args) + "\n")
		}
	}
	if seed.Len() == 0 {
		return
	}
	b.WriteString("    configManagementPlugin:\n")
	b.WriteString(seed.String())
}

func writeMatchDiscover(b *strings.Builder, discover *pluginpolicy.PluginDiscoverMatch) {
	b.WriteString("    match:\n")
	b.WriteString("      discover:\n")
	writeDiscoverFields(b, "        ", discover)
}

func writeDirectDiscover(b *strings.Builder, indent string, discover *pluginpolicy.PluginDiscoverMatch) {
	b.WriteString(indent + "discover:\n")
	writeDiscoverFields(b, indent+"  ", discover)
}

func writeDiscoverFields(b *strings.Builder, indent string, discover *pluginpolicy.PluginDiscoverMatch) {
	if discover.FileName != "" {
		b.WriteString(indent + "fileName: " + quote(discover.FileName) + "\n")
	}
	if discover.FindGlob != "" {
		b.WriteString(indent + "find:\n")
		b.WriteString(indent + "  glob: " + quote(discover.FindGlob) + "\n")
	}
}

func writeContainerFields(b *strings.Builder, plugin PluginReport, opts GenerateOptions) {
	image, allowMutable, comment := generatedImage(plugin, opts)
	if opts.Comments && comment != "" {
		b.WriteString("    # " + comment + "\n")
	}
	b.WriteString("    image: " + quote(image) + "\n")
	if allowMutable {
		b.WriteString("    allowMutableImageTag: true\n")
	}
	b.WriteString("    network: none\n")
}

func generatedImage(plugin PluginReport, opts GenerateOptions) (image string, allowMutable bool, comment string) {
	if plugin.Sidecar.Confidence == SidecarConfidenceAmbiguous {
		return PlaceholderImage, false, "Multiple sidecar image candidates were found; replace the placeholder with the trusted plugin image."
	}
	if plugin.Sidecar.Candidate == nil || strings.TrimSpace(plugin.Sidecar.Candidate.Image) == "" {
		return PlaceholderImage, false, "Replace the placeholder with the trusted plugin image."
	}
	candidate := strings.TrimSpace(plugin.Sidecar.Candidate.Image)
	if imageAccepted(candidate, false) {
		return candidate, false, fmt.Sprintf("Image inferred from %s sidecar %s.", plugin.Sidecar.Candidate.Source, plugin.Sidecar.Candidate.Name)
	}
	if opts.AllowMutableImageTags && imageAccepted(candidate, true) {
		return candidate, true, fmt.Sprintf("Mutable tag inferred from %s sidecar %s. Digest pinning is recommended for CI.", plugin.Sidecar.Candidate.Source, plugin.Sidecar.Candidate.Name)
	}
	return PlaceholderImage, false, fmt.Sprintf("Tag-only image candidate %q was inferred; rerun with --allow-mutable-image-tags or replace the placeholder with a digest-pinned image.", candidate)
}

func imageAccepted(value string, allowMutable bool) bool {
	ref, err := reference.Parse(value)
	if err != nil {
		return false
	}
	named, ok := ref.(reference.Named)
	if !ok || reference.Domain(named) == "" {
		return false
	}
	if _, ok := ref.(reference.Digested); ok {
		return true
	}
	if _, ok := ref.(reference.Tagged); !ok {
		return false
	}
	return allowMutable
}

func writeLifecycle(b *strings.Builder, plugin PluginReport, opts GenerateOptions) {
	command := plugin.Generate
	if len(command) == 0 || !plugin.GenerateSafe || !commandAccepted(command) {
		if opts.Comments && len(command) > 0 {
			b.WriteString("    # CMP generate command " + quote(strings.Join(command, " ")) + " needs a direct trusted executable argv.\n")
		}
		command = []string{PlaceholderCommandToken}
	}
	b.WriteString("    generate:\n")
	b.WriteString("      command: " + yamlStringSequence(command) + "\n")
}

func writeEnv(b *strings.Builder, plugin PluginReport) {
	if len(plugin.Env) == 0 {
		return
	}
	var env []string
	for _, name := range plugin.Env {
		name = strings.TrimSpace(name)
		if envNameAccepted(name) {
			env = append(env, name)
		}
	}
	if len(env) == 0 {
		return
	}
	sort.Strings(env)
	b.WriteString("    env:\n")
	b.WriteString("      allow:\n")
	for _, name := range env {
		b.WriteString("        - " + quote(name) + "\n")
	}
}

func writeParameters(b *strings.Builder, plugin PluginReport) {
	if len(plugin.Parameters) == 0 {
		return
	}
	parameters := append([]ParameterEvidence(nil), plugin.Parameters...)
	sort.Slice(parameters, func(i, j int) bool { return parameters[i].Name < parameters[j].Name })
	parameters = validParameters(parameters)
	if len(parameters) == 0 {
		return
	}
	b.WriteString("    parameters:\n")
	b.WriteString("      allow:\n")
	for _, parameter := range parameters {
		b.WriteString("        - name: " + quote(parameter.Name) + "\n")
		b.WriteString("          type: " + string(parameter.Type) + "\n")
	}
}

func cleanArgv(input []string) []string {
	out := make([]string, 0, len(input))
	for _, value := range input {
		value = strings.TrimSpace(value)
		if value == "" {
			return nil
		}
		out = append(out, value)
	}
	return out
}

func commandAccepted(command []string) bool {
	if len(command) == 0 {
		return false
	}
	for _, token := range command {
		if strings.TrimSpace(token) == "" {
			return false
		}
	}
	argv0 := command[0]
	if strings.ContainsAny(argv0, `/\`) && !strings.HasPrefix(argv0, "/") {
		return false
	}
	return !isDeniedCommand(argv0)
}

var envNamePattern = regexp.MustCompile(`^[A-Za-z_][A-Za-z0-9_]*$`)

func envNameAccepted(name string) bool {
	if !envNamePattern.MatchString(name) {
		return false
	}
	upper := strings.ToUpper(name)
	switch upper {
	case "PATH", "ARGOCD_APP_PARAMETERS", "BASH_ENV", "ENV", "PYTHONPATH", "PYTHONHOME", "PYTHONSTARTUP", "RUBYOPT", "RUBYLIB", "NODE_OPTIONS", "NODE_PATH", "PERL5LIB", "PERL5OPT", "PSMODULEPATH", "POWERSHELL_TELEMETRY_OPTOUT":
		return false
	}
	return !strings.HasPrefix(upper, "LD_") && !strings.HasPrefix(upper, "DYLD_") && !strings.HasPrefix(upper, "PARAM_")
}

var parameterNamePattern = regexp.MustCompile(`^[A-Za-z0-9_.-]+$`)

func validParameters(parameters []ParameterEvidence) []ParameterEvidence {
	seenEnv := map[string]string{}
	var out []ParameterEvidence
	for _, parameter := range parameters {
		name := strings.TrimSpace(parameter.Name)
		if !parameterNamePattern.MatchString(name) {
			continue
		}
		envName := parameterEnvName(name)
		if existing, ok := seenEnv[envName]; ok && existing != name {
			continue
		}
		seenEnv[envName] = name
		switch parameter.Type {
		case pluginpolicy.ExecParameterTypeString, pluginpolicy.ExecParameterTypeArray, pluginpolicy.ExecParameterTypeMap:
		default:
			continue
		}
		out = append(out, ParameterEvidence{Name: name, Type: parameter.Type})
	}
	return out
}

func parameterEnvName(name string) string {
	name = strings.ToUpper(name)
	return regexp.MustCompile(`[^A-Z0-9_]`).ReplaceAllString(name, "_")
}

func commentUseSummary(uses []PluginUse) string {
	if len(uses) == 0 {
		return "no discovered Applications"
	}
	first := uses[0]
	summary := first.AppNamespace + "/" + first.AppName
	if len(uses) > 1 {
		summary += fmt.Sprintf(" and %d more", len(uses)-1)
	}
	return summary
}

func yamlStringSequence(values []string) string {
	items := make([]string, 0, len(values))
	for _, value := range values {
		items = append(items, quote(value))
	}
	return "[" + strings.Join(items, ", ") + "]"
}

func quote(value string) string {
	return strconv.Quote(value)
}

var dnsLabelInvalid = regexp.MustCompile(`[^a-z0-9-]+`)

func bootstrapName(plugin, sourcePath string) string {
	name := strings.ToLower(plugin + "-" + strings.ReplaceAll(sourcePath, "/", "-"))
	name = dnsLabelInvalid.ReplaceAllString(name, "-")
	name = strings.Trim(name, "-")
	if name == "" {
		name = "plugin-bootstrap"
	}
	return trimDNSLabel(name)
}

func trimDNSLabel(value string) string {
	value = strings.Trim(value, "-")
	if len(value) <= 63 {
		return value
	}
	return strings.Trim(value[:63], "-")
}

func cleanBootstrapSourcePath(value string) string {
	value = strings.TrimSpace(value)
	if value == "." {
		return "."
	}
	value = strings.Trim(value, "/")
	clean, ok := cleanRelativePath(value)
	if !ok {
		return ""
	}
	return clean
}
